/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Submissions = {
  _id: string;
  _type: "submissions";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  date?: string;
  name?: string;
  email?: string;
  topic?: string;
  message?: string;
};

export type PrivacyPolicy = {
  _id: string;
  _type: "privacyPolicy";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  mainTitle?: string;
  policyContent?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  confirmedButton?: string;
  language?: "pl" | "en" | "jp";
};

export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  navigations?: {
    home?: string;
    voiceActing?: string;
    lessons?: string;
    training?: string;
    contact?: string;
  };
  languageSwitcher?: string;
  language?: "pl" | "en" | "jp";
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type VoiceActing = {
  _id: string;
  _type: "voiceActing";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  mainTitle?: string;
  mainDescription?: string;
  audioSection?: {
    titleAudioSection?: string;
    selectSong?: string;
    audioFiles?: Array<{
      audioName?: string;
      file?: {
        asset?: SanityFileAssetReference;
        media?: unknown;
        _type: "file";
      };
      _type: "audio";
      _key: string;
    }>;
  };
  videoSection?: {
    titleVideoSection?: string;
    viewYTButton?: string;
  };
  language?: "pl" | "en" | "jp";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Training = {
  _id: string;
  _type: "training";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  mainTitle?: string;
  mainDescription?: string;
  personalTreningCard?: {
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    title?: string;
    description?: string;
    button?: string;
  };
  pilatesTreningCard?: {
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    title?: string;
    description?: string;
    button?: string;
  };
  language?: "pl" | "en" | "jp";
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  contactEmail?: string;
  socials?: {
    instagram?: {
      url?: string;
      handle?: string;
    };
    tiktok?: {
      url?: string;
      handle?: string;
    };
    youtube?: {
      url?: string;
      handle?: string;
    };
    twitch?: {
      url?: string;
      handle?: string;
    };
    x?: {
      url?: string;
      handle?: string;
    };
  };
  webstieName?: string;
  websiteFavicon?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  cssVariables?: string;
};

export type Lessons = {
  _id: string;
  _type: "lessons";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  leftSide?: {
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    title?: string;
    description?: string;
  };
  rightSide?: {
    title?: string;
    description?: string;
    englishCard?: {
      title?: string;
      description?: string;
    };
    japaneseCard?: {
      title?: string;
      description?: string;
    };
  };
  contactCard?: {
    title?: string;
    description?: string;
    nameButton?: string;
  };
  language?: "pl" | "en" | "jp";
};

export type Home = {
  _id: string;
  _type: "home";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  mainTitle?: string;
  mainDescription?: string;
  cardsHome?: Array<{
    cardTitile?: string;
    cardDescription?: string;
    _type: "card";
    _key: string;
  }>;
  language?: "pl" | "en" | "jp";
};

export type Contact = {
  _id: string;
  _type: "contact";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  mainTitle?: string;
  mainDescription?: string;
  emailTitle?: string;
  socialsTitle?: string;
  contactForm?: {
    formTitle?: string;
    nameField?: {
      name?: string;
      namePlaceholder?: string;
    };
    emailField?: {
      email?: string;
      emailPlaceholder?: string;
    };
    topicField?: {
      title?: string;
      topicPlaceholder?: string;
      topicContent?: Array<string>;
    };
    messageField?: {
      message?: string;
      messagePlaceholder?: string;
    };
    submitButton?: string;
    policyInforamation?: {
      policyText?: string;
      linkButton?: string;
    };
  };
  confirmationMessage?: {
    titleSuccess?: string;
    descriptionSuccess?: string;
    titleFailed?: string;
    descriptionFailed?: string;
    sendingMessage?: string;
  };
  language?: "pl" | "en" | "jp";
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | Submissions
  | PrivacyPolicy
  | Navigation
  | SanityFileAssetReference
  | VoiceActing
  | SanityImageAssetReference
  | Training
  | SanityImageCrop
  | SanityImageHotspot
  | Settings
  | Lessons
  | Home
  | Contact
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: sanity/lib/queries.ts
// Variable: settingsQuery
// Query: *[_type == "settings"][0]
export type SettingsQueryResult = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  contactEmail?: string;
  socials?: {
    instagram?: {
      url?: string;
      handle?: string;
    };
    tiktok?: {
      url?: string;
      handle?: string;
    };
    youtube?: {
      url?: string;
      handle?: string;
    };
    twitch?: {
      url?: string;
      handle?: string;
    };
    x?: {
      url?: string;
      handle?: string;
    };
  };
  webstieName?: string;
  websiteFavicon?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  cssVariables?: string;
} | null;

// Source: sanity/lib/queries.ts
// Variable: homeQuery
// Query: *[_type == "home" && language == $language][0]{    "mainImageUrl": mainImage.asset->url,    mainTitle,    mainDescription,    cardsHome[]{      cardTitile,      cardDescription    },    language  }
export type HomeQueryResult = {
  mainImageUrl: string | null;
  mainTitle: string | null;
  mainDescription: string | null;
  cardsHome: Array<{
    cardTitile: string | null;
    cardDescription: string | null;
  }> | null;
  language: "en" | "jp" | "pl" | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: voiceActingQuery
// Query: *[_type == "voiceActing" && language == $language][0]{    _id,    mainTitle,    mainDescription,    audioSection{      titleAudioSection,      selectSong,      audioFiles[]{        'id': _key,        'title': audioName,        "src": file.asset->url,      }    },    videoSection{      titleVideoSection,      viewYTButton,    },        language  }
export type VoiceActingQueryResult = {
  _id: string;
  mainTitle: string | null;
  mainDescription: string | null;
  audioSection: {
    titleAudioSection: string | null;
    selectSong: string | null;
    audioFiles: Array<{
      id: string;
      title: string | null;
      src: string | null;
    }> | null;
  } | null;
  videoSection: {
    titleVideoSection: string | null;
    viewYTButton: string | null;
  } | null;
  language: "en" | "jp" | "pl" | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: lessonsQuery
// Query: *[_type == "lessons" && language == $language][0] {  _id,  leftSide {    title,    description,    image {      asset->{        url,        metadata      }    }  },  rightSide {    title,    description,    englishCard {      title,      description    },    japaneseCard {      title,      description    }  },  contactCard {    title,    description,    nameButton  },  language}
export type LessonsQueryResult = {
  _id: string;
  leftSide: {
    title: string | null;
    description: string | null;
    image: {
      asset: {
        url: string | null;
        metadata: SanityImageMetadata | null;
      } | null;
    } | null;
  } | null;
  rightSide: {
    title: string | null;
    description: string | null;
    englishCard: {
      title: string | null;
      description: string | null;
    } | null;
    japaneseCard: {
      title: string | null;
      description: string | null;
    } | null;
  } | null;
  contactCard: {
    title: string | null;
    description: string | null;
    nameButton: string | null;
  } | null;
  language: "en" | "jp" | "pl" | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: trainingQuery
// Query: *[_type == "training" && language == $language][0] {  _id,  mainTitle,  mainDescription,  personalTreningCard {    title,    description,    button,    image {      asset->{        url,        metadata      }    }  },  pilatesTreningCard {    title,    description,    button,    image {      asset->{        url,        metadata      }    }  },  language}
export type TrainingQueryResult = {
  _id: string;
  mainTitle: string | null;
  mainDescription: string | null;
  personalTreningCard: {
    title: string | null;
    description: string | null;
    button: string | null;
    image: {
      asset: {
        url: string | null;
        metadata: SanityImageMetadata | null;
      } | null;
    } | null;
  } | null;
  pilatesTreningCard: {
    title: string | null;
    description: string | null;
    button: string | null;
    image: {
      asset: {
        url: string | null;
        metadata: SanityImageMetadata | null;
      } | null;
    } | null;
  } | null;
  language: "en" | "jp" | "pl" | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: contactQuery
// Query: *[_type == "contact" && language == $language][0] {  _id,  mainTitle,  mainDescription,  emailTitle,  socialsTitle,  contactForm {    formTitle,    nameField {      name,      namePlaceholder    },    emailField {      email,      emailPlaceholder    },    topicField {      title,      topicPlaceholder,      topicContent    },    messageField {      message,      messagePlaceholder    },    submitButton,    policyInforamation {      policyText,      linkButton    }  },  confirmationMessage {    titleSuccess,    descriptionSuccess,    titleFailed,    descriptionFailed,    sendingMessage  },  language}
export type ContactQueryResult = {
  _id: string;
  mainTitle: string | null;
  mainDescription: string | null;
  emailTitle: string | null;
  socialsTitle: string | null;
  contactForm: {
    formTitle: string | null;
    nameField: {
      name: string | null;
      namePlaceholder: string | null;
    } | null;
    emailField: {
      email: string | null;
      emailPlaceholder: string | null;
    } | null;
    topicField: {
      title: string | null;
      topicPlaceholder: string | null;
      topicContent: Array<string> | null;
    } | null;
    messageField: {
      message: string | null;
      messagePlaceholder: string | null;
    } | null;
    submitButton: string | null;
    policyInforamation: {
      policyText: string | null;
      linkButton: string | null;
    } | null;
  } | null;
  confirmationMessage: {
    titleSuccess: string | null;
    descriptionSuccess: string | null;
    titleFailed: string | null;
    descriptionFailed: string | null;
    sendingMessage: string | null;
  } | null;
  language: "en" | "jp" | "pl" | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: privacyPolicyQuery
// Query: *[_type == "privacyPolicy"&& language == $language][0] {  _id,  mainTitle,  policyContent,  confirmedButton,  language}
export type PrivacyPolicyQueryResult = {
  _id: string;
  mainTitle: string | null;
  policyContent: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  confirmedButton: string | null;
  language: "en" | "jp" | "pl" | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: navigation
// Query: *[_type == "navigation" && language == $language][0] {  _id,  navigations {    home,    voiceActing,    lessons,    training,    contact  },  languageSwitcher,  language}
export type NavigationResult = {
  _id: string;
  navigations: {
    home: string | null;
    voiceActing: string | null;
    lessons: string | null;
    training: string | null;
    contact: string | null;
  } | null;
  languageSwitcher: string | null;
  language: "en" | "jp" | "pl" | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "settings"][0]': SettingsQueryResult;
    '\n  *[_type == "home" && language == $language][0]{\n    "mainImageUrl": mainImage.asset->url,\n    mainTitle,\n    mainDescription,\n    cardsHome[]{\n      cardTitile,\n      cardDescription\n    },\n    language\n  }\n': HomeQueryResult;
    "\n  *[_type == \"voiceActing\" && language == $language][0]{\n    _id,\n    mainTitle,\n    mainDescription,\n\n    audioSection{\n      titleAudioSection,\n      selectSong,\n      audioFiles[]{\n        'id': _key,\n        'title': audioName,\n        \"src\": file.asset->url,\n      }\n    },\n\n    videoSection{\n      titleVideoSection,\n      viewYTButton,\n    },\n    \n    language\n  }\n": VoiceActingQueryResult;
    '*[_type == "lessons" && language == $language][0] {\n  _id,\n  leftSide {\n    title,\n    description,\n    image {\n      asset->{\n        url,\n        metadata\n      }\n    }\n  },\n  rightSide {\n    title,\n    description,\n    englishCard {\n      title,\n      description\n    },\n    japaneseCard {\n      title,\n      description\n    }\n  },\n  contactCard {\n    title,\n    description,\n    nameButton\n  },\n  language\n}': LessonsQueryResult;
    '*[_type == "training" && language == $language][0] {\n  _id,\n  mainTitle,\n  mainDescription,\n  personalTreningCard {\n    title,\n    description,\n    button,\n    image {\n      asset->{\n        url,\n        metadata\n      }\n    }\n  },\n  pilatesTreningCard {\n    title,\n    description,\n    button,\n    image {\n      asset->{\n        url,\n        metadata\n      }\n    }\n  },\n  language\n}': TrainingQueryResult;
    '*[_type == "contact" && language == $language][0] {\n  _id,\n  mainTitle,\n  mainDescription,\n  emailTitle,\n  socialsTitle,\n  contactForm {\n    formTitle,\n    nameField {\n      name,\n      namePlaceholder\n    },\n    emailField {\n      email,\n      emailPlaceholder\n    },\n    topicField {\n      title,\n      topicPlaceholder,\n      topicContent\n    },\n    messageField {\n      message,\n      messagePlaceholder\n    },\n    submitButton,\n    policyInforamation {\n      policyText,\n      linkButton\n    }\n  },\n  confirmationMessage {\n    titleSuccess,\n    descriptionSuccess,\n    titleFailed,\n    descriptionFailed,\n    sendingMessage\n  },\n  language\n}': ContactQueryResult;
    '*[_type == "privacyPolicy"&& language == $language][0] {\n  _id,\n  mainTitle,\n  policyContent,\n  confirmedButton,\n  language\n}': PrivacyPolicyQueryResult;
    '*[_type == "navigation" && language == $language][0] {\n  _id,\n  navigations {\n    home,\n    voiceActing,\n    lessons,\n    training,\n    contact\n  },\n  languageSwitcher,\n  language\n}': NavigationResult;
  }
}
