/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Contact = {
  _id: string;
  _type: "contact";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  mainTitle?: string;
  mainDescription?: string;
  emailTitle?: string;
  email?: string;
  language?: "pl" | "en" | "jp";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Training = {
  _id: string;
  _type: "training";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  mainTitle?: string;
  mainDescription?: string;
  personalTreningCard?: {
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    title?: string;
    description?: string;
    button?: string;
  };
  pilatesTreningCard?: {
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    title?: string;
    description?: string;
    button?: string;
  };
  language?: "pl" | "en" | "jp";
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Lessons = {
  _id: string;
  _type: "lessons";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  leftSide?: {
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    title?: string;
    description?: string;
  };
  rightSide?: {
    title?: string;
    description?: string;
    englishCard?: {
      title?: string;
      description?: string;
    };
    japaneseCard?: {
      title?: string;
      description?: string;
    };
  };
  contactard?: {
    title?: string;
    description?: string;
    nameButton?: string;
  };
  language?: "pl" | "en" | "jp";
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type VoiceActing = {
  _id: string;
  _type: "voiceActing";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  mainTitle?: string;
  mainDescription?: string;
  audioSection?: {
    titleAudioSection?: string;
    audioFiles?: Array<{
      audioName?: string;
      file?: {
        asset?: SanityFileAssetReference;
        media?: unknown;
        _type: "file";
      };
      _type: "audio";
      _key: string;
    }>;
  };
  videoSection?: {
    titleVideoSection?: string;
    viewYTButton?: string;
    videoBackup?: Array<string>;
  };
  language?: "pl" | "en" | "jp";
};

export type Home = {
  _id: string;
  _type: "home";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  mainTitle?: string;
  mainDescription?: string;
  cardsHome?: Array<{
    cardTitile?: string;
    cardDescription?: string;
    _type: "card";
    _key: string;
  }>;
  language?: "pl" | "en" | "jp";
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | Contact
  | SanityImageAssetReference
  | Training
  | SanityImageCrop
  | SanityImageHotspot
  | Lessons
  | SanityFileAssetReference
  | VoiceActing
  | Home
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: sanity/lib/queries.ts
// Variable: homeQuery
// Query: *[_type == "home" && language == $language][0]{    "mainImageUrl": mainImage.asset->url,    mainTitle,    mainDescription,    cardsHome[]{      cardTitile,      cardDescription    },    language  }
export type HomeQueryResult = {
  mainImageUrl: string | null;
  mainTitle: string | null;
  mainDescription: string | null;
  cardsHome: Array<{
    cardTitile: string | null;
    cardDescription: string | null;
  }> | null;
  language: "en" | "jp" | "pl" | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "home" && language == $language][0]{\n    "mainImageUrl": mainImage.asset->url,\n    mainTitle,\n    mainDescription,\n    cardsHome[]{\n      cardTitile,\n      cardDescription\n    },\n    language\n  }\n': HomeQueryResult;
  }
}
